### ISSUE TITLE
async http/https request method and websocket need to be supported

### ISSUE THREAD

**Issue by ErosZy** [rryqszq4/ngx_php7#107]
This is a very good project, but the existing socket request method is too low-level. If it is to be used more, asynchronous http/https request method and websocket need to be supported.

**Comment by rryqszq4** [comment]
@ErosZy 
Thanks for your attention. These are achievable, like https://github.com/rryqszq4/ngx_php7/blob/master/t/lib/mysql.php, but they are missing now.
