### ISSUE TITLE
Try to add OPcache

### ISSUE THREAD

**Issue by joanhey** [rryqszq4/ngx_php7#72]
We could try that:
https://bugs.php.net/bug.php?id=65078

And if work without problem, create a bug request to add the ngx_php7 sapi.

**Comment by rryqszq4** [comment]
![WechatIMG4243](https://user-images.githubusercontent.com/3954194/67655952-63b4a980-f98d-11e9-8712-96777ec8d89d.jpeg)  

@joanhey Not startup, I think need a add request~

**Comment by rryqszq4** [comment]
The name is better with 'php-ngx' 
https://github.com/rryqszq4/ngx_php7/blob/master/src/php/impl/php_ngx.c#L263

**Comment by joanhey** [comment]
Had you tried to add "php-ngx" in https://github.com/php/php-src/blob/master/ext/opcache/ZendAccelerator.c#L2544 ??

Copile it to try with php-ngx.

**Comment by rryqszq4** [comment]
I am trying something else.

**Comment by joanhey** [comment]
https://github.com/unbit/uwsgi/blob/master/plugins/php/php_plugin.c

The uwsgi, perhaps they initialize the sapi in another way.

**Comment by joanhey** [comment]
In nginx unit it's working without problems.
https://github.com/nginx/unit/blob/master/src/nxt_php_sapi.c

**Comment by rryqszq4** [comment]
I think that "cli-server" maybe better.

**Comment by joanhey** [comment]
With "cli-server"
![DeepinScreenshot_20191028170015](https://user-images.githubusercontent.com/249085/67694968-928a4a00-f9a4-11e9-821a-013be80af374.png)

**Comment by joanhey** [comment]
I need to test a little more.
With different files.

**Comment by joanhey** [comment]
I don't expect any exponencial gain.
But all the includes will be fast now.

**Comment by rryqszq4** [comment]
@joanhey Test use opcache and not.
1. Result of use opcache
```
./wrk -H 'Host: 127.0.0.1' -H 'Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 512 --timeout 8 -t 28 http://127.0.0.1/h2
Running 15s test @ http://127.0.0.1/h2
  28 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   109.19ms  538.96ms   6.81s    97.50%
    Req/Sec     1.77k     1.66k   10.61k    81.66%
  Latency Distribution
     50%    2.47ms
     75%    3.53ms
     90%  200.55ms
     99%    3.21s 
  627719 requests in 15.10s, 81.39MB read
  Socket errors: connect 0, read 10, write 0, timeout 4
Requests/sec:  41570.54
Transfer/sec:      5.39MB
```

2. Result of not use opcache
```
./wrk -H 'Host: 127.0.0.1' -H 'Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 512 --timeout 8 -t 28 http://127.0.0.1/h2
Running 15s test @ http://127.0.0.1/h2
  28 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   508.66ms    1.27s    7.91s    89.15%
    Req/Sec   198.26    158.90     1.46k    61.65%
  Latency Distribution
     50%   49.07ms
     75%   52.63ms
     90%    2.09s 
     99%    5.82s 
  30416 requests in 15.10s, 3.94MB read
  Socket errors: connect 0, read 0, write 0, timeout 3
Requests/sec:   2014.45
Transfer/sec:    267.46KB
```

And cache is hit.
![WechatIMG1943](https://user-images.githubusercontent.com/3954194/67832528-e0c25900-fb1c-11e9-906a-a765044fbd85.jpeg)

Finally, but still be wary of unexpected mistakes.

**Comment by joanhey** [comment]
The socket errors happen without opcache too, so I think it is for the 512 concurrent connections in that computer.

The numbers are impressive.
What is the code of that test ??

**Comment by rryqszq4** [comment]
Very easy code~
```
location = /h1 {
        content_by_php '
                echo "hello, world!"
        ';
}

 location = /h2 {
        content_by_php '
                include "/ngx_php7/t/lib/hello.php";
        ';
}
```

**Comment by joanhey** [comment]
And the results of /h1 ??

**Comment by rryqszq4** [comment]
No, it's h2

**Comment by joanhey** [comment]
yes,
but I want to compare /h1 vs /h2 (with opcache)

**Comment by rryqszq4** [comment]
OK, show you the result at tomorrow.

**Comment by rryqszq4** [comment]
@joanhey 
3. Result h1 of use opcache
```
./wrk -H 'Host: 127.0.0.1' -H 'Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 512 --timeout 8 -t 28 http://127.0.0.1/h1
Running 15s test @ http://127.0.0.1/h1
  28 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    66.11ms  355.81ms   6.77s    98.54%
    Req/Sec     1.99k     2.11k   43.31k    84.85%
  Latency Distribution
     50%    2.37ms
     75%    3.31ms
     90%  170.52ms
     99%    1.05s 
  679166 requests in 15.10s, 88.06MB read
Requests/sec:  44976.38
Transfer/sec:      5.83MB
```
4. Result h2 of not use opcache
```
./wrk -H 'Host: 127.0.0.1' -H 'Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 512 --timeout 8 -t 28 http://127.0.0.1/h1
Running 15s test @ http://127.0.0.1/h1
  28 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    60.00ms  305.88ms   6.77s    98.38%
    Req/Sec     1.84k     1.86k   11.82k    86.27%
  Latency Distribution
     50%    2.32ms
     75%    3.71ms
     90%  167.79ms
     99%  779.61ms
  660201 requests in 15.10s, 85.60MB read
  Socket errors: connect 0, read 0, write 0, timeout 27
Requests/sec:  43725.02
Transfer/sec:      5.67MB
```
![WechatIMG1988](https://user-images.githubusercontent.com/3954194/67915020-c1830480-fbcc-11e9-9ea2-12492af8d892.jpeg)

**Comment by joanhey** [comment]
Could you create a new tag, to tests in the benchmark.
And check the results with opcache and the changes in the async mysql.

**Comment by rryqszq4** [comment]
> Could you create a new tag, to tests in the benchmark.
> And check the results with opcache and the changes in the async mysql.

OK, I will release the version as soon as possible.

**Comment by joanhey** [comment]
Now the image with the hello world is not correct.

![](https://raw.githubusercontent.com/rryqszq4/ngx_php7/master/docs/hello_world_performance.png)

The php file is almost as fast as inline.

**Comment by rryqszq4** [comment]
Sure that the image was already legacy.
